Updates package name for issue #1
agustinmulet/gatsbyworkshop pull request #3
Opened 2019-10-28 12:11 UTC by goncy

2019-10-28 12:12 UTC, goncy commented
Este contiene el otro commit asi que tendria que ser mergeado despues

2019-10-28 16:25 UTC, agustinmulet requested changes
Gracias goncy por el PR :D

2019-10-28 16:25 UTC, agustinmulet commented on src/pages/paso-01.mdx
> +          /* En el próximo paso vamos a ver como seria la query */
Me gustaaaa!! Ahí pude probarlo y anda genial, lo que sí, se puede cambiar el texto por "En el próximo paso vamos a ver cómo sería la query"? 😊

2019-10-28 16:25 UTC, agustinmulet commented on src/pages/paso-01.mdx
> +      token: `nuestro-token-va-aca`,
Y acá si se puede cambiar el "aca" por "acá" 😇

2019-10-29 22:31 UTC, agustinmulet approved these changes

2019-10-29 22:33 UTC, merged